### ISSUE TITLE
Using tinyxml2 breaks Flood WebUI

### ISSUE THREAD

**Issue by zp** [rakshasa/rtorrent#1330]
Building latest master of rtorrent ([5a200f5](https://github.com/rakshasa/rtorrent/commit/5a200f5d8f8bc8ed28dfc948321451585f724b15)) with ```./configure --disable-debug --enable-ipv6 --with-xmlrpc-tinyxml2``` causes [Flood WebUI](https://github.com/jesec/flood) to break with the following error msg.
```
Error: Unexpected XML-RPC Tag: int
    at closeTag (/snapshot/flood/server/services/rTorrent/util/XMLRPCDeserializer.ts:94:22)
    at parse (/snapshot/flood/node_modules/saxen/dist/index.js:1063:11)
    at Parser3.Parser3.parse (/snapshot/flood/node_modules/saxen/dist/index.js:302:5)
    at <anonymous> (/snapshot/flood/server/services/rTorrent/util/XMLRPCDeserializer.ts:121:12)
    at new Promise (<anonymous>)
    at Object.deserialize (/snapshot/flood/server/services/rTorrent/util/XMLRPCDeserializer.ts:112:3)
    at <anonymous> (/snapshot/flood/server/services/rTorrent/util/scgiUtil.ts:43:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/snapshot/flood/node_modules/p-queue/dist/index.js:118:36)
```
Not sure if this is an error on rtorrent's end or if Flood needs to be updated (I would assume rtorrent if tinyxml2 is supposed to be a drop-in replacement)

Flood works with xmlrpc-c on the same commit, and also works with the [xml-as-json](https://github.com/jesec/rtorrent/tree/refactor/xml-as-json) branch of jesec's rtorrent fork

I don't have a ruTorrent setup currently to check if it works with tinyxml2.

**Comment by rakshasa** [comment]
This should be fixed in the tinyxml2 code we imported.

**Comment by kannibalox** [comment]
`<int>` is technically part of the XMLRPC spec, but no sense locking out clients if everyone understands `<i4>` equally well.

**Comment by kannibalox** [comment]
> `methodReponse` -> `methodResponse`
> 
> Flood appears to work after implementing i4 + typo fix

Oof, thanks for pointing that out, turns out the clients I've been using don't bother checking the element name and just grab the first child indiscriminately. I've updated the PR.

**Comment by trim21** [comment]
if int is part of xmlrpc spec this should be fixed in flood

**Comment by kannibalox** [comment]
It's the lack of explicit empty parameters (`<params></params>`) that's throwing things off. The spec leaves it up to the implementation, but I've updated https://github.com/rakshasa/rtorrent/pull/1331 to match xmlrpc-c's behavior.

**Comment by trim21** [comment]
int type fixed in flood
