### ISSUE TITLE
rtorrent 0.10 crash

### ISSUE THREAD

**Issue by laplacesdaemon** [rakshasa/rtorrent#1333]
rtorrent 0.10.0 keeps crashing at random times while seeding. Sometimes it takes more than a day, sometimes just a couple hours.

I'm on Archlinux. Build options:

CFLAGS="-march=native -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \
         -Wl,-z,pack-relative-relocs"
 
I've tried both with LTO enabled and disabled. I've also tried with strict aliasing enabled and disabled. No difference.

gdb bt:
```
#0  0x000076d00dea53f4 in ?? () from /usr/lib/libc.so.6
#1  0x000076d00de4c120 in raise () from /usr/lib/libc.so.6
#2  0x000076d00de334c3 in abort () from /usr/lib/libc.so.6
#3  0x000064e1be4651cd in do_panic (signum=11) at main.cc:643
#4  <signal handler called>
#5  std::__new_allocator<torrent::ChunkPart>::construct<torrent::ChunkPart, torrent::ChunkPart> (this=0x64e2068055f0, __p=0x64e1fc90fbd0) at /usr/include/c++/14.2.1/bits/new_allocator.h:189
#6  std::allocator_traits<std::allocator<torrent::ChunkPart> >::construct<torrent::ChunkPart, torrent::ChunkPart> (__a=..., __p=0x64e1fc90fbd0) at /usr/include/c++/14.2.1/bits/alloc_traits.h:534
#7  std::__relocate_object_a<torrent::ChunkPart, torrent::ChunkPart, std::allocator<torrent::ChunkPart> > (__dest=0x64e1fc90fbd0, __orig=0x64e206a2ce90, __alloc=...) at /usr/include/c++/14.2.1/bits/stl_uninitialized.h:1075
#8  std::__relocate_a_1<torrent::ChunkPart*, torrent::ChunkPart*, std::allocator<torrent::ChunkPart> > (__first=0x64e206a2ce90, __last=<optimized out>, __result=0x64e1fc90fbd0, __alloc=...)
    at /usr/include/c++/14.2.1/bits/stl_uninitialized.h:1103
#9  std::__relocate_a<torrent::ChunkPart*, torrent::ChunkPart*, std::allocator<torrent::ChunkPart> > (__first=<optimized out>, __last=<optimized out>, __result=0x64e1fc90fbd0, __alloc=...)
    at /usr/include/c++/14.2.1/bits/stl_uninitialized.h:1145
#10 std::vector<torrent::ChunkPart, std::allocator<torrent::ChunkPart> >::_S_do_relocate (__first=<optimized out>, __last=<optimized out>, __result=0x64e1fc90fbd0, __alloc=...) at /usr/include/c++/14.2.1/bits/stl_vector.h:495
#11 std::vector<torrent::ChunkPart, std::allocator<torrent::ChunkPart> >::_S_relocate (__first=<optimized out>, __last=<optimized out>, __result=0x64e1fc90fbd0, __alloc=...) at /usr/include/c++/14.2.1/bits/stl_vector.h:512
#12 std::vector<torrent::ChunkPart, std::allocator<torrent::ChunkPart> >::_M_realloc_insert<torrent::ChunkPart> (this=0x64e2068055f0, __position=...) at /usr/include/c++/14.2.1/bits/vector.tcc:518
#13 std::vector<torrent::ChunkPart, std::allocator<torrent::ChunkPart> >::_M_insert_rval (this=0x64e2068055f0, __position=..., __v=...) at /usr/include/c++/14.2.1/bits/vector.tcc:379
#14 std::vector<torrent::ChunkPart, std::allocator<torrent::ChunkPart> >::insert (this=0x64e2068055f0, __position=..., __x=...) at /usr/include/c++/14.2.1/bits/stl_vector.h:1396
#15 torrent::Chunk::push_back (this=this@entry=0x64e2068055f0, mapped=mapped@entry=torrent::ChunkPart::MAPPED_MMAP, c=...) at data/chunk.cc:88
#16 0x000076d00e3678dd in torrent::FileList::create_chunk (this=0x64e1f37a4868, offset=264762555, length=2885, prot=1) at data/file_list.cc:626
#17 0x000076d00e3ab0c3 in std::function<torrent::Chunk* (unsigned int, int)>::operator()(unsigned int, int) const (this=0x64e1f37856d8, __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/14.2.1/bits/std_function.h:591
#18 torrent::ChunkList::get (this=0x64e1f3785670, index=1009, flags=flags@entry=0) at data/chunk_list.cc:148
#19 0x000076d00e3e4720 in torrent::PeerConnectionBase::load_up_chunk (this=this@entry=0x64e1f62530e0) at protocol/peer_connection_base.cc:381
#20 0x000076d00e3e7e09 in torrent::PeerConnection<(torrent::Download::ConnectionType)1>::event_write (this=0x64e1f62530e0) at protocol/peer_connection_leech.cc:610
#21 0x000076d00e3a0779 in torrent::PollEPoll::perform (this=0x64e1ec41c210) at poll_epoll.cc:190
#22 0x000076d00e393099 in torrent::thread_base::event_loop (thread=0x64e1ec422810) at utils/thread_base.cc:150
#23 0x000064e1be49d9ce in main (argc=1, argv=0x7ffd5425e938) at main.cc:506

```

**Comment by rakshasa** [comment]
You need to start by testing which, if any, of the flags are triggering the issue.

Specifically the protection and pointer flags.

**Comment by laplacesdaemon** [comment]
Arch finally has official packages for the new version. Have been trying them for a few days and it is rock solid. Closing for now.

**Comment by laplacesdaemon** [comment]
The culprit was march=native. With march=x86-64 it does not crash (the official packages use march=x86-64). This is on an AMD Zen 3 CPU.

**Comment by laplacesdaemon** [comment]
The culprit was march=native. With march=x86-64 it does not crash (this is the how official packages are bult) I'm on a Zen 3 AMD CPU.

Anyway, this is most probably a compiler issue.
