### ISSUE TITLE
rtorrent 0.10 core dumped when quitting

### ISSUE THREAD

**Issue by laplacesdaemon** [rakshasa/rtorrent#1336]
With the official Arch Linux packages for rtorrent 0.10.0 sometimes a core is dumped when stopping rtorrent (via INT signal from a systemd unit). The session is saved correctly and the announces seem to reach the trackers. This is with 5000+ torrents.

```
#0  0x00007d20018a53f4 in ?? () from /usr/lib/libc.so.6
#1  0x00007d200184c120 in raise () from /usr/lib/libc.so.6
#2  0x00007d20018334c3 in abort () from /usr/lib/libc.so.6
#3  0x000062e5e1a249b8 in do_panic (signum=11) at /usr/src/debug/rtorrent/rtorrent/src/main.cc:634
#4  <signal handler called>
#5  0x000062e5e1ac9929 in torrent::thread_base::poll (this=<optimized out>, this=<optimized out>)
    at /usr/include/torrent/utils/thread_base.h:56
#6  core::CurlSocket::close (this=0x62e635c95e10) at core/curl_socket.cc:103
#7  core::CurlSocket::receive_socket (easy_handle=<optimized out>, fd=<optimized out>, what=<optimized out>, 
    userp=<optimized out>, socketp=0x62e635c95e10) at core/curl_socket.cc:62
#8  0x00007d2001e5c866 in ?? () from /usr/lib/libcurl.so.4
#9  0x00007d2001ea5d1d in ?? () from /usr/lib/libcurl.so.4
#10 0x00007d2001e13cf7 in ?? () from /usr/lib/libcurl.so.4
#11 0x00007d2001e25926 in ?? () from /usr/lib/libcurl.so.4
#12 0x00007d2001e8ebf7 in ?? () from /usr/lib/libcurl.so.4
#13 0x00007d2001e2635e in ?? () from /usr/lib/libcurl.so.4
#14 0x00007d2001e126e2 in ?? () from /usr/lib/libcurl.so.4
#15 0x00007d2001e1bdae in ?? () from /usr/lib/libcurl.so.4
#16 0x00007d2001e2342d in ?? () from /usr/lib/libcurl.so.4
#17 0x00007d2001e23bcd in ?? () from /usr/lib/libcurl.so.4
#18 0x00007d2001e23e28 in ?? () from /usr/lib/libcurl.so.4
#19 0x00007d2001e5d5db in curl_multi_cleanup () from /usr/lib/libcurl.so.4
#20 0x000062e5e1a48dd8 in core::CurlStack::~CurlStack (this=<optimized out>, this=<optimized out>)
    at core/curl_stack.cc:72
#21 core::Manager::cleanup (this=<optimized out>) at core/manager.cc:199
#22 Control::cleanup (this=<optimized out>) at /usr/src/debug/rtorrent/rtorrent/src/control.cc:140
#23 main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/rtorrent/rtorrent/src/main.cc:500
```

**Comment by kannibalox** [comment]
This is the same issue as https://github.com/rakshasa/rtorrent/issues/1302, which has a PR open for it: https://github.com/rakshasa/rtorrent/pull/1338

**Comment by laplacesdaemon** [comment]
> This is the same issue as #1302, which has a PR open for it: #1338

Thanks. I will try the patch. In my case I was just seeding.
