### ISSUE TITLE
Feature request: Check if disk is full and give a sane report if rtorrent crashes.

### ISSUE THREAD

**Issue by ironhouzi** [rakshasa/rtorrent#240]
I had this problem: https://github.com/rakshasa/rtorrent/issues/39 and it would have saved me a lot of time if rtorrent would have checked this for me.

This is of course due to my own fault, but it would still be a nice feature for rtorrent to have.
Thanks for a great piece of software.

**Comment by ilf** [comment]
Same here. Had the segfault (again), because my drive was full (again). Obviously, PEBCAK, but a check and helpful error message (instead of a crash) would be awesome. Thanks!

**Comment by rakshasa** [comment]
There's supposed to be a disk space checking event scheduled every 30 seconds (iirc). Might want to fiddle with that so that it runs more often and/or requires more free diskspace available before stopping relevant downloads.

**Comment by AniketSK** [comment]
How about checking what the maximum chunk size for any of your torrents is and setting the minimum free space to that?
I think this should be done differently entirely to let it fail whenever it fails and catch it at that time. Still a feature request though a different one from the original here.

**Comment by mrvn** [comment]
I have this in my .rtorrent:

    # Close torrents when diskspace is low.
    schedule = low_diskspace,5,60,close_low_diskspace=2000M
 
But with a maximum download speed of 13MiB/s that can get to 500MB free before stopping.

As a side note: Filesystems get realy realy realy realy slow when they get full. If you run rtorrent till the disk reports ENOSPC it will easily cache multiple GB of data in memory waiting to be written. Then what do you do with that data? You can't write it. You don't want to throw it away. Your system will start swapping making disks even slower. Conclusion: You want to stop early.

AniketSK: I think rtorrent should sum up all partial and unwritten chunks and subtract that from the free disk space. What remains should be used as basis for the low_diskspace check. And instead of doing the check every 30 seconds why not check it before starting a new block?

**Comment by EdwardBetts** [comment]
I have an example of rtorrent crashing during startup because the disk is full. You could check for disk space at startup.

    $ rtorrent 'magnet:?xt=urn:btih:bc84cb84010074094dba7bb55eebf68c6b3934a2&dn=debian-8.2.0-amd64-CD-1.iso&tr=udp://bttracker.debian.org:6969&tr=http://bttracker.debian.org:6969/announce'
    Caught SIGBUS, dumping stack:
    rtorrent() [0x415f4b]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x10760) [0x7fe76c57f760]
    /lib/x86_64-linux-gnu/libc.so.6(+0x90759) [0x7fe76c25c759]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0x7f8f2) [0x7fe76daec8f2]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xc8ceb) [0x7fe76db35ceb]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xd3524) [0x7fe76db40524]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xbf1de) [0x7fe76db2c1de]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xc098d) [0x7fe76db2d98d]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xc9223) [0x7fe76db36223]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(+0xd4240) [0x7fe76db41240]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0x14a) [0x7fe76daafd6a]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x61) [0x7fe76daafe11]
    /usr/lib/x86_64-linux-gnu/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x124) [0x7fe76daeb334]
    rtorrent() [0x412094]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fe76c1ec850]
    rtorrent() [0x415356]
    
    Error: Success
    Signal code '2': Non-existent physical address.
    Fault address: 0x7fe76e65f000
    The fault address is not part of any chunk.
    Aborted (core dumped)
    $ df -h ~/mnt
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/loop0      8.7M  8.5M     0 100% /home/edward/mnt
    $

**Comment by EdwardBetts** [comment]
Here is a backtrace from gdb:

    Program received signal SIGBUS, Bus error.
    __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
    #0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
    #1  0x00007ffff73d2e73 in torrent::Chunk::from_buffer (this=0xa5a940, buffer=0x99decd, position=0, length=16384) at chunk.cc:240
    #2  0x00007ffff7446155 in torrent::PeerConnectionBase::down_chunk_process (this=0xa46fa0, buffer=0x99decd, length=16384) at peer_connection_base.cc:632
    #3  0x00007ffff74546af in torrent::PeerConnectionMetadata::receive_metadata_piece (this=0xa46fa0, piece=0, data=0x99decd "d6:lengthi657457152e4:name27:debian-8.2.0-amd64-CD-1.iso12:piece lengthi524288e6:pieces25080:\"n\354\362=\202L\243\347x4\250q'\024\224\002\215d\002\313\020\316\366t\301\351/@\345\331_\bGj[k\022Sg\375pW)L\237\216\252\017\254Y\341\244\256FϮ&a\202\033\062d\275,\025xP\r\306!\344Ӎ\214\066q\n\227\255a0LI\331\017y\262\300\216\215\341\322\001a\225\205\n\366\214\035տ\bPi", length=16384) at peer_connection_metadata.cc:478
    #4  0x00007ffff7436ac8 in torrent::ProtocolExtension::parse_ut_metadata (this=0xa46e40) at extensions.cc:374
    #5  0x00007ffff7436340 in torrent::ProtocolExtension::read_done (this=0xa46e40) at extensions.cc:249
    #6  0x00007ffff74468de in torrent::PeerConnectionBase::down_extension (this=0xa46fa0) at peer_connection_base.cc:725
    #7  0x00007ffff745320b in torrent::PeerConnectionMetadata::event_read (this=0xa46fa0) at peer_connection_metadata.cc:261
    #8  0x00007ffff7363a29 in torrent::PollEPoll::perform (this=0x8b60c0) at poll_epoll.cc:185
    #9  0x00007ffff7363ca0 in torrent::PollEPoll::do_poll (this=0x8b60c0, timeout_usec=653977, flags=0) at poll_epoll.cc:219
    #10 0x00007ffff73d13e7 in torrent::thread_base::event_loop (thread=0x8b2cc0) at thread_base.cc:174
    #11 0x0000000000414360 in main (argc=2, argv=0x7fffffffe278) at main.cc:857

**Comment by EdwardBetts** [comment]
Pull request: https://github.com/rakshasa/libtorrent/pull/93
