### ISSUE TITLE
random segfault while downloading

### ISSUE THREAD

**Issue by pcaneill** [rakshasa/rtorrent#350]
Hi there.

I had a segfault when downloading a file.
I am not able to reproduce it, and there are no particular configuration of my client.
I have only a backtrace, I hope it might give you a hint.
I can provide more information if needed.

Here is the backtrace:

```
#0  0x00006e7572d5f107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00006e7572d604e8 in __GI_abort () at abort.c:89
#2  0x00006e757364ab3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00006e7573648bb6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00006e7573648c01 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00006e7573648e19 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00006e75744ef709 in torrent::FileList::left_bytes (this=0x2ff4ff8) at file_list.cc:162
#7  0x0000000000452350 in _M_call<torrent::FileList*> (__ptr=<optimized out>, this=0x2d95a10) at /usr/include/c++/4.9/functional:611
#8  operator()<torrent::FileList*, void> (__object=<optimized out>, this=0x2d95a10) at /usr/include/c++/4.9/functional:657
#9  __call<long unsigned int, core::Download*&&, const torrent::Object&, 0ul> (__args=<optimized out>, this=0x2d95a10) at /usr/include/c++/4.9/functional:1264
#10 operator()<core::Download*, const torrent::Object&, long unsigned int> (this=0x2d95a10) at /usr/include/c++/4.9/functional:1323
#11 std::_Function_handler<torrent::Object (core::Download*, torrent::Object const&), std::_Bind<std::_Mem_fn<unsigned long (torrent::FileList::*)() const> (std::_Bind<std::_Mem_fn<torrent::FileList* (core::Download::*)()> (std::_Placeholder<1>)>)> >::_M_invoke(std::_Any_data const&, core::Download*, torrent::Object const&) (__functor=..., __args#0=<optimized out>, __args#1=...) at /usr/include/c++/4.9/functional:2024
#12 0x00000000004d56f5 in operator() (__args#1=..., __args#0=<optimized out>, this=0x2d959c8) at /usr/include/c++/4.9/functional:2439
#13 _call<std::function<torrent::Object(core::Download*, const torrent::Object&)>, core::Download*, torrent::Object> (args=..., target=..., cmd=0x2d959c8) at command.h:247
#14 rpc::command_base_call<core::Download*> (rawCommand=0x2d959c8, target=..., args=...) at command.cc:59
#15 0x00000000004dd860 in rpc::CommandMap::call_command (this=0x752520 <rpc::commands>, key=0x6e7570838690 "d.left_bytes", arg=..., target=...) at command_map.cc:171
#16 0x00000000004ec70a in rpc::parse_command (target=..., first=0x6 <error: Cannot access memory at address 0x6>, last=0x6e7564059dc5 "") at parse_commands.cc:166
#17 0x0000000000465266 in d_multicall (args=std::vector of length 43, capacity 43 = {...}) at command_events.cc:303
#18 0x000000000041d24c in __call<torrent::Object, rpc::rt_triple<int, void*, void*>&&, const std::vector<torrent::Object, std::allocator<torrent::Object> >&, 0ul> (__args=<optimized out>, this=<optimized out>) at /usr/include/c++/4.9/functional:1264
#19 operator()<rpc::rt_triple<int, void*, void*>, const std::vector<torrent::Object, std::allocator<torrent::Object> >&, torrent::Object> (this=<optimized out>) at /usr/include/c++/4.9/functional:1323
#20 std::_Function_handler<torrent::Object (rpc::rt_triple<int, void*, void*>, std::vector<torrent::Object, std::allocator<torrent::Object> > const&), std::_Bind<torrent::Object (*(std::_Placeholder<2>))(std::vector<torrent::Object, std::allocator<torrent::Object> > const&)> >::_M_invoke(std::_Any_data const&, rpc::rt_triple<int, void*, void*>, std::vector<torrent::Object, std::allocator<torrent::Object> > const&) (
    __functor=..., __args#0=..., __args#1=...) at /usr/include/c++/4.9/functional:2025
#21 0x00000000004dccb2 in std::function<torrent::Object (rpc::rt_triple<int, void*, void*>, std::vector<torrent::Object, std::allocator<torrent::Object> > const&)>::operator()(rpc::rt_triple<int, void*, void*>, std::vector<torrent::Object, std::allocator<torrent::Object> > const&) const (this=this@entry=0x2d868a8, __args#0=..., __args#1=std::vector of length 43, capacity 43 = {...}) at /usr/include/c++/4.9/functional:2439
#22 0x00000000004dd29c in _call<std::function<torrent::Object(rpc::rt_triple<int, void*, void*>, const std::vector<torrent::Object>&)>, rpc::rt_triple<int, void*, void*>, std::vector<torrent::Object> > (args=std::vector of length -3795333684306, capacity -3795333684306 = {...}, target=..., cmd=0x2d868a8) at command.h:247
#23 rpc::command_base_call_list<rpc::rt_triple<int, void*, void*> > (rawCommand=0x2d868a8, target=..., rawArgs=...) at command.cc:125
#24 0x00000000004dd6ed in rpc::CommandMap::call_command (this=<optimized out>, itr=..., itr@entry=..., arg=..., target=...) at command_map.cc:176
#25 0x00000000004f573d in rpc::xmlrpc_call_command (env=0x6e7570838c90, args=0x6e7564057ab0, voidServerInfo=<optimized out>) at xmlrpc.cc:495
#26 0x00006e757429ad38 in callNamedMethod (resultPP=0x6e7570838cc0, callInfoP=0x0, paramArrayP=0x6e7564057ab0, methodP=<optimized out>, envP=0x6e7570838c90) at registry.c:312
#27 xmlrpc_dispatchCall (envP=envP@entry=0x6e7570838c90, registryP=registryP@entry=0x2da7810, methodName=0x6e75640011f0 "d.multicall2", paramArrayP=0x6e7564057ab0, callInfoP=callInfoP@entry=0x0, resultPP=resultPP@entry=0x6e7570838cc0) at registry.c:337
#28 0x00006e757429ae24 in xmlrpc_registry_process_call2 (envP=0x6e7570838d30, registryP=0x2da7810, callXml=0x6e756402f480 "<?xml version=\"1.0\" encoding=\"UTF-8\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param>"..., callXmlLen=2849, callInfo=callInfo@entry=0x0, 
    responseXmlPP=responseXmlPP@entry=0x6e7570838d18) at registry.c:426
#29 0x00006e757429af97 in xmlrpc_registry_process_call (envP=<optimized out>, registryP=<optimized out>, host=<optimized out>, callXml=<optimized out>, callXmlLen=<optimized out>) at registry.c:466
#30 0x00000000004f3732 in rpc::XmlRpc::process(char const*, unsigned int, std::function<bool (char const*, unsigned int)>) (this=0x752480 <rpc::xmlrpc>, inBuffer=inBuffer@entry=0x6e756402f480 "<?xml version=\"1.0\" encoding=\"UTF-8\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param>"..., 
    length=length@entry=2849, slotWrite=...) at xmlrpc.cc:534
#31 0x00000000004f2118 in rpc::SCgi::receive_call (this=<optimized out>, task=<optimized out>, buffer=0x6e756402f480 "<?xml version=\"1.0\" encoding=\"UTF-8\"?><methodCall><methodName>d.multicall2</methodName><params><param><value><string></string></value></param><param><value><string>main</string></value></param><param>"..., length=2849) at scgi.cc:175
#32 0x00000000004f2d42 in rpc::SCgiTask::event_read (this=0x2dcd450) at scgi_task.cc:191
#33 0x00006e75744e18d0 in torrent::PollEPoll::perform (this=this@entry=0x2d5e6b0) at poll_epoll.cc:185
#34 0x00006e75744e1991 in torrent::PollEPoll::do_poll (this=0x2d5e6b0, timeout_usec=<optimized out>, flags=<optimized out>) at poll_epoll.cc:219
#35 0x00006e757451b8a4 in torrent::thread_base::event_loop (thread=0x2d5ca60) at thread_base.cc:174
#36 0x00006e75738fd0a4 in start_thread (arg=0x6e7570839700) at pthread_create.c:309
#37 0x00006e7572e1004d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

And the version

```
Rakshasa's BitTorrent client version 0.9.4.
```

**Comment by rakshasa** [comment]
Closing as old.
