### ISSUE TITLE
Segfault in torrent::DhtServer::find_node_next

### ISSUE THREAD

**Issue by infernix** [rakshasa/rtorrent#534]
This is with 0.9.6 and libtorrent 0.13.6

Backtrace:

```
#0  0x00007fabb7058067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 4200
        selftid = 4200
#1  0x00007fabb7059448 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0xb, sa_sigaction = 0xb}, sa_mask = {__val = {
              374517928, 140730139917232, 140375522328007, 5, 0, 15537104, 140375486537000, 
              140375501093824, 140730139917232, 140730139916816, 140375522353893, 0, 15756624, 
              140375515105856, 0, 0}}, sa_flags = 0, sa_restorer = 0xf06d30}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000004139d5 in do_panic (signum=11) at main.cc:994
        output = <incomplete type>
        stackPtrs = {0x413852 <do_panic(int)+146>, 0x44bdea <SignalHandler::caught(int)+58>, 
          0x7fabb70580e0 <__restore_rt>, 
          0x7fabb88e9172 <torrent::DhtServer::find_node_next(torrent::DhtTransactionSearch*)+194>, 
          0x7fabb88e9aa6 <torrent::DhtServer::parse_find_node_reply(torrent::DhtTransactionSearch*, torrent::raw_string)+326>, 
          0x7fabb88e9c66 <torrent::DhtServer::process_response(torrent::HashString const&, rak::socket_address const*, torrent::DhtMessage const&)+342>, 
          0x7fabb88ea04b <torrent::DhtServer::event_read()+715>, 
          0x7fabb8898620 <torrent::PollEPoll::perform()+224>, 
          0x7fabb88986f1 <torrent::PollEPoll::do_poll(long, int)+97>, 
          0x7fabb88cf757 <torrent::thread_base::event_loop(torrent::thread_base*)+295>, 
          0x4123b7 <main(int, char**)+10423>, 0x7fabb7044b45 <__libc_start_main+245>, 
          0x413314 <_start+41>, 0x0, 0x1007fabb75fe9d8, 0xa7, 0x7fabb893f6e8, 0x726, 0x722, 0xaee9670}
        stackSize = <optimized out>
        stackStrings = <optimized out>
```

I have a bt full if needed. This looks like https://github.com/rakshasa/rtorrent/issues/294 

Here's at least the first part of the bt full:
```
#0  0x00007fabb7058067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 4200
        selftid = 4200
#1  0x00007fabb7059448 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0xb, sa_sigaction = 0xb}, sa_mask = {__val = {
              374517928, 140730139917232, 140375522328007, 5, 0, 15537104, 140375486537000, 
              140375501093824, 140730139917232, 140730139916816, 140375522353893, 0, 15756624, 
              140375515105856, 0, 0}}, sa_flags = 0, sa_restorer = 0xf06d30}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000004139d5 in do_panic (signum=11) at main.cc:994
        output = <incomplete type>
        stackPtrs = {0x413852 <do_panic(int)+146>, 0x44bdea <SignalHandler::caught(int)+58>, 
          0x7fabb70580e0 <__restore_rt>, 
          0x7fabb88e9172 <torrent::DhtServer::find_node_next(torrent::DhtTransactionSearch*)+194>, 
          0x7fabb88e9aa6 <torrent::DhtServer::parse_find_node_reply(torrent::DhtTransactionSearch*, torrent::raw_string)+326>, 
          0x7fabb88e9c66 <torrent::DhtServer::process_response(torrent::HashString const&, rak::socket_address const*, torrent::DhtMessage const&)+342>, 
          0x7fabb88ea04b <torrent::DhtServer::event_read()+715>, 
          0x7fabb8898620 <torrent::PollEPoll::perform()+224>, 
          0x7fabb88986f1 <torrent::PollEPoll::do_poll(long, int)+97>, 
          0x7fabb88cf757 <torrent::thread_base::event_loop(torrent::thread_base*)+295>, 
          0x4123b7 <main(int, char**)+10423>, 0x7fabb7044b45 <__libc_start_main+245>, 
          0x413314 <_start+41>, 0x0, 0x1007fabb75fe9d8, 0xa7, 0x7fabb893f6e8, 0x726, 0x722, 0xaee9670}
        stackSize = <optimized out>
        stackStrings = <optimized out>
---Type <return> to continue, or q <return> to quit---
#3  0x000000000044bdea in operator() (this=<optimized out>) at /usr/include/c++/4.9
```

Any ideas? Or is this a libtorrent issue?

**Comment by infernix** [comment]
So far, seems to have fixed itself by deleting dht cache.
