### ISSUE TITLE
XMLRPC load.start fails being treated as hash string

### ISSUE THREAD

**Issue by RealAlexJones** [rakshasa/rtorrent#627]
This is a regression when building from git.

Sent XMLRPC
```
<?xml version='1.0'?>
<methodCall>
    <methodName>load.start</methodName>
    <params>
        <param>
            <value><string>torrent.txt.torrent</string></value>
        </param>
    </params>
</methodCall>
```

Response
```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-501</i4></value></member>
<member><name>faultString</name>
<value><string>Unsupported target type found.</string></value></member>
</struct></value>
</fault>
</methodResponse>
```

in rpc::xmlrpc_to_target
The value type is XMLRPC_TYPE_STRING

It seems that this path is expecting hashes that can have suffixes :f/t/p

```
    if (std::strlen(str) == 40) {
      ::free((void*)str);
      return rpc::make_target(download);
    }

    if (std::strlen(str) < 42 || str[40] != ':') {
      ::free((void*)str);
      throw xmlrpc_error(XMLRPC_TYPE_ERROR, "Unsupported target type found.");

```

Callstack to failure 
```
(gdb) bt
#0  rpc::xmlrpc_to_target (env=env@entry=0x7f7d7fffec20, value=0x7f7d78004f60) at xmlrpc.cc:137
#1  0x000000000051a3e9 in rpc::xmlrpc_to_object (env=env@entry=0x7f7d7fffec20, value=value@entry=0x7f7d78005060, callType=callType@entry=1,
    target=target@entry=0x7f7d7fffe9f0) at xmlrpc.cc:327
#2  0x000000000051d4c3 in rpc::xmlrpc_call_command (env=0x7f7d7fffec20, args=0x7f7d78005060, voidServerInfo=<optimized out>) at xmlrpc.cc:490
#3  0x00007f7d86a4c018 in xmlrpc_dispatchCall () from /usr/lib64/libxmlrpc_server.so.3
#4  0x00007f7d86a4c128 in xmlrpc_registry_process_call2 () from /usr/lib64/libxmlrpc_server.so.3
#5  0x00007f7d86a4c295 in xmlrpc_registry_process_call () from /usr/lib64/libxmlrpc_server.so.3
#6  0x0000000000519886 in rpc::XmlRpc::process(char const*, unsigned int, std::function<bool (char const*, unsigned int)>) (this=0x778740 <rpc::xmlrpc>,
    inBuffer=inBuffer@entry=0x7f7d7800099e "<?xml version='1.0'?>\n<methodCall>\n<methodName>load.start</methodName>\n<params>\n<param>\n<value><string>torrent.txt.torrent</string></value>\n</param>\n</params>\n</methodCall>\n", length=length@entry=173, slotWrite=...) at xmlrpc.cc:534
#7  0x0000000000518398 in rpc::SCgi::receive_call (this=<optimized out>, task=task@entry=0x1d2f0e8,
    buffer=0x7f7d7800099e "<?xml version='1.0'?>\n<methodCall>\n<methodName>load.start</methodName>\n<params>\n<param>\n<value><string>torrent.txt.torrent</string></value>\n</param>\n</params>\n</methodCall>\n", length=173) at scgi.cc:175
#8  0x0000000000518b62 in rpc::SCgiTask::event_read (this=0x1d2f0e8) at scgi_task.cc:191
#9  0x00007f7d8731525a in torrent::PollEPoll::perform (this=this@entry=0x1cde480) at poll_epoll.cc:185
#10 0x00007f7d873152fd in torrent::PollEPoll::do_poll (this=0x1cde480, timeout_usec=<optimized out>, flags=<optimized out>) at poll_epoll.cc:224
#11 0x00007f7d87359674 in torrent::thread_base::event_loop (thread=0x1cdd8c0) at thread_base.cc:174
#12 0x00007f7d85c993b4 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f7d850d4aed in clone () from /lib64/libc.so.6
```

**Comment by kannibalox** [comment]
Try feeding in a blank string for the target as the first parameter, and then the file path as the second. This was an intentional change I believe, and applies to many other commands as well.

**Comment by RealAlexJones** [comment]
Thank you for your response. 

Adding a blank string value before the file target does return a different response, but my .torrent is still not loaded. 

Request
```
<?xml version='1.0'?>
<methodCall>
    <methodName>load.start</methodName>
    <params>
        <param>
            <value><string></string></value>
        </param>
        <param>
            <value><string>torrent.txt.torrent</string></value>
        </param>    
    </params>
</methodCall>
```

Response

```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><i4>0</i4></value></param>
</params>
</methodResponse>
```

I've confirmed that the .torrent is valid.
